version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo

  task-service:
    build: ./task-service
    ports:
      - "3003:3003"
    env_file:
      - ./task-service/.env
    depends_on:
      - mongo

  orchestrator:
    build: ./orchestrator
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - task-service

volumes:
  mongo-data:
